name = "chat-service"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
# 开发环境变量
ENVIRONMENT = "development"

# 生产环境需要设置的secret变量 (使用 wrangler secret put 命令设置):
# DEEPSEEK_API_KEY = "your-deepseek-api-key"
# ALLOWED_ORIGINS = "https://your-frontend-domain.com,http://localhost:3000"

# CORS 设置
[env.production]
name = "chat-service-prod"

[env.development]
name = "chat-service-dev"